In [42]:
from pandas import DataFrame
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [2]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

In [4]:
df = pd.read_csv(url, names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'label'])
df

sepal_length  sepal_width  petal_length  petal_width           label
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
6             4.6          3.4           1.4          0.3     Iris-setosa
7             5.0          3.4           1.5          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
9             4.9          3.1           1.5          0.1     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
11            4.8          3.4           1.6          0.2     Iris-setosa
12            4.8          3.0           1.4          0.1     Iris-setosa
13            4.3          3.0           1.1          0.1     Iris-setosa
14            5.8          4.0           1.2          0.2     Iris-setosa
15            5.7          4.4           1.5          0.4     Iris-setosa
16            5.4          3.9           1.3          0.4     Iris-setosa
17            5.1          3.5           1.4          0.3     Iris-setosa
18            5.7          3.8           1.7          0.3     Iris-setosa
19            5.1          3.8           1.5          0.3     Iris-setosa
20            5.4          3.4           1.7          0.2     Iris-setosa
21            5.1          3.7           1.5          0.4     Iris-setosa
22            4.6          3.6           1.0          0.2     Iris-setosa
23            5.1          3.3           1.7          0.5     Iris-setosa
24            4.8          3.4           1.9          0.2     Iris-setosa
25            5.0          3.0           1.6          0.2     Iris-setosa
26            5.0          3.4           1.6          0.4     Iris-setosa
27            5.2          3.5           1.5          0.2     Iris-setosa
28            5.2          3.4           1.4          0.2     Iris-setosa
29            4.7          3.2           1.6          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
120           6.9          3.2           5.7          2.3  Iris-virginica
121           5.6          2.8           4.9          2.0  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica
123           6.3          2.7           4.9          1.8  Iris-virginica
124           6.7          3.3           5.7          2.1  Iris-virginica
125           7.2          3.2           6.0          1.8  Iris-virginica
126           6.2          2.8           4.8          1.8  Iris-virginica
127           6.1          3.0           4.9          1.8  Iris-virginica
128           6.4          2.8           5.6          2.1  Iris-virginica
129           7.2          3.0           5.8          1.6  Iris-virginica
130           7.4          2.8           6.1          1.9  Iris-virginica
131           7.9          3.8           6.4          2.0  Iris-virginica
132           6.4          2.8           5.6          2.2  Iris-virginica
133           6.3          2.8           5.1          1.5  Iris-virginica
134           6.1          2.6           5.6          1.4  Iris-virginica
135           7.7          3.0           6.1          2.3  Iris-virginica
136           6.3          3.4           5.6          2.4  Iris-virginica
137           6.4          3.1           5.5          1.8  Iris-virginica
138           6.0          3.0           4.8          1.8  Iris-virginica
139           6.9          3.1           5.4          2.1  Iris-virginica
140           6.7          3.1           5.6          2.4  Iris-virginica
141           6.9          3.1           5.1          2.3  Iris-virginica
142      

In [5]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [6]:
df.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.109369      0.871754     0.817954
sepal_width      -0.109369     1.000000     -0.420516    -0.356544
petal_length      0.871754    -0.420516      1.000000     0.962757
petal_width       0.817954    -0.356544      0.962757     1.000000

In [8]:
x = df.loc[:, ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']].values
x

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 4

In [10]:
# before dimensionality reduction on x make sure to standard normalize the data
scaler = StandardScaler()
normal_x = scaler.fit_transform(x)
normal_x

array([[ -9.00681170e-01,   1.03205722e+00,  -1.34127240e+00,
         -1.31297673e+00],
       [ -1.14301691e+00,  -1.24957601e-01,  -1.34127240e+00,
         -1.31297673e+00],
       [ -1.38535265e+00,   3.37848329e-01,  -1.39813811e+00,
         -1.31297673e+00],
       [ -1.50652052e+00,   1.06445364e-01,  -1.28440670e+00,
         -1.31297673e+00],
       [ -1.02184904e+00,   1.26346019e+00,  -1.34127240e+00,
         -1.31297673e+00],
       [ -5.37177559e-01,   1.95766909e+00,  -1.17067529e+00,
         -1.05003079e+00],
       [ -1.50652052e+00,   8.00654259e-01,  -1.34127240e+00,
         -1.18150376e+00],
       [ -1.02184904e+00,   8.00654259e-01,  -1.28440670e+00,
         -1.31297673e+00],
       [ -1.74885626e+00,  -3.56360566e-01,  -1.34127240e+00,
         -1.31297673e+00],
       [ -1.14301691e+00,   1.06445364e-01,  -1.28440670e+00,
         -1.44444970e+00],
       [ -5.37177559e-01,   1.49486315e+00,  -1.28440670e+00,
         -1.31297673e+00],
       [ -1.26418478e

In [11]:
print(normal_x.mean())
print(normal_x.std())

-2.48689957516e-16
1.0


In [13]:
pca1 = PCA()
components = pca1.fit_transform(normal_x)
components

array([[ -2.26454173e+00,   5.05703903e-01,  -1.21943348e-01,
         -2.30733235e-02],
       [ -2.08642550e+00,  -6.55404729e-01,  -2.27250832e-01,
         -1.03208244e-01],
       [ -2.36795045e+00,  -3.18477311e-01,   5.14796236e-02,
         -2.78252250e-02],
       [ -2.30419716e+00,  -5.75367713e-01,   9.88604444e-02,
          6.63114622e-02],
       [ -2.38877749e+00,   6.74767397e-01,   2.14278490e-02,
          3.73972870e-02],
       [ -2.07053681e+00,   1.51854856e+00,   3.06842583e-02,
         -4.39877494e-03],
       [ -2.44571134e+00,   7.45626750e-02,   3.42197636e-01,
          3.80965668e-02],
       [ -2.23384186e+00,   2.47613932e-01,  -8.25744645e-02,
          2.55051623e-02],
       [ -2.34195768e+00,  -1.09514636e+00,   1.53562399e-01,
          2.67938291e-02],
       [ -2.18867576e+00,  -4.48629048e-01,  -2.46559522e-01,
          3.99073035e-02],
       [ -2.16348656e+00,   1.07059558e+00,  -2.64009373e-01,
         -1.53011377e-02],
       [ -2.32737775e

In [14]:
pca1.explained_variance_ratio_

array([ 0.72770452,  0.23030523,  0.03683832,  0.00515193])

In [15]:
pca2 = PCA(n_components=2)
components2 = pca2.fit_transform(normal_x)

In [16]:
pca2.explained_variance_ratio_

array([ 0.72770452,  0.23030523])

In [17]:
df2 = DataFrame(components2, columns=['pc1', 'pc2'])
df2

pc1       pc2
0   -2.264542  0.505704
1   -2.086426 -0.655405
2   -2.367950 -0.318477
3   -2.304197 -0.575368
4   -2.388777  0.674767
5   -2.070537  1.518549
6   -2.445711  0.074563
7   -2.233842  0.247614
8   -2.341958 -1.095146
9   -2.188676 -0.448629
10  -2.163487  1.070596
11  -2.327378  0.158587
12  -2.224083 -0.709118
13  -2.639716 -0.938282
14  -2.192292  1.889979
15  -2.251465  2.722371
16  -2.202750  1.513750
17  -2.190179  0.514304
18  -1.894074  1.431111
19  -2.339949  1.158033
20  -1.914556  0.430465
21  -2.204645  0.952457
22  -2.774170  0.489517
23  -1.820412  0.106751
24  -2.228217  0.162186
25  -1.957024 -0.607893
26  -2.052063  0.266014
27  -2.168194  0.552016
28  -2.140306  0.336640
29  -2.268790 -0.314879
..        ...       ...
120  2.040496  0.907399
121  0.973915 -0.571174
122  2.898064  0.397791
123  1.329194 -0.486761
124  1.704241  1.014148
125  1.957728  1.003335
126  1.171905 -0.318897
127  1.019781  0.065543
128  1.786009 -0.193273
129  1.864778  0.555382
130  2.435497  0.246654
131  2.316082  2.626184
132  1.860371 -0.184672
133  1.111272 -0.295986
134  1.197469 -0.817168
135  2.800949  0.844748
136  1.580155  1.072474
137  1.347044  0.422256
138  0.923433  0.019230
139  1.853552  0.672423
140  2.016157  0.610397
141  1.903117  0.686025
142  1.153190 -0.701326
143  2.043308  0.864685
144  2.001691  1.048550
145  1.870522  0.382822
146  1.558492 -0.905314
147  1.520845  0.266795
148  1.376391  1.016362
149  0.959299 -0.022284

[150 rows x 2 columns]

In [18]:
df2['label'] = df['label']
df2

pc1       pc2           label
0   -2.264542  0.505704     Iris-setosa
1   -2.086426 -0.655405     Iris-setosa
2   -2.367950 -0.318477     Iris-setosa
3   -2.304197 -0.575368     Iris-setosa
4   -2.388777  0.674767     Iris-setosa
5   -2.070537  1.518549     Iris-setosa
6   -2.445711  0.074563     Iris-setosa
7   -2.233842  0.247614     Iris-setosa
8   -2.341958 -1.095146     Iris-setosa
9   -2.188676 -0.448629     Iris-setosa
10  -2.163487  1.070596     Iris-setosa
11  -2.327378  0.158587     Iris-setosa
12  -2.224083 -0.709118     Iris-setosa
13  -2.639716 -0.938282     Iris-setosa
14  -2.192292  1.889979     Iris-setosa
15  -2.251465  2.722371     Iris-setosa
16  -2.202750  1.513750     Iris-setosa
17  -2.190179  0.514304     Iris-setosa
18  -1.894074  1.431111     Iris-setosa
19  -2.339949  1.158033     Iris-setosa
20  -1.914556  0.430465     Iris-setosa
21  -2.204645  0.952457     Iris-setosa
22  -2.774170  0.489517     Iris-setosa
23  -1.820412  0.106751     Iris-setosa
24  -2.228217  0.162186     Iris-setosa
25  -1.957024 -0.607893     Iris-setosa
26  -2.052063  0.266014     Iris-setosa
27  -2.168194  0.552016     Iris-setosa
28  -2.140306  0.336640     Iris-setosa
29  -2.268790 -0.314879     Iris-setosa
..        ...       ...             ...
120  2.040496  0.907399  Iris-virginica
121  0.973915 -0.571174  Iris-virginica
122  2.898064  0.397791  Iris-virginica
123  1.329194 -0.486761  Iris-virginica
124  1.704241  1.014148  Iris-virginica
125  1.957728  1.003335  Iris-virginica
126  1.171905 -0.318897  Iris-virginica
127  1.019781  0.065543  Iris-virginica
128  1.786009 -0.193273  Iris-virginica
129  1.864778  0.555382  Iris-virginica
130  2.435497  0.246654  Iris-virginica
131  2.316082  2.626184  Iris-virginica
132  1.860371 -0.184672  Iris-virginica
133  1.111272 -0.295986  Iris-virginica
134  1.197469 -0.817168  Iris-virginica
135  2.800949  0.844748  Iris-virginica
136  1.580155  1.072474  Iris-virginica
137  1.347044  0.422256  Iris-virginica
138  0.923433  0.019230  Iris-virginica
139  1.853552  0.672423  Iris-virginica
140  2.016157  0.610397  Iris-virginica
141  1.903117  0.686025  Iris-virginica
142  1.153190 -0.701326  Iris-virginica
143  2.043308  0.864685  Iris-virginica
144  2.001691  1.048550  Iris-virginica
145  1.870522  0.382822  Iris-virginica
146  1.558492 -0.905314  Iris-virginica
147  1.520845  0.266795  Iris-virginica
148  1.376391  1.016362  Iris-virginica
149  0.959299 -0.022284  Iris-virginica

[150 rows x 3 columns]

In [25]:
df2['label'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [31]:
d1 = df2[df2['label'] == 'Iris-setosa']
d1['label'] = 0
d1

/home/mehul/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


pc1       pc2  label
0  -2.264542  0.505704      0
1  -2.086426 -0.655405      0
2  -2.367950 -0.318477      0
3  -2.304197 -0.575368      0
4  -2.388777  0.674767      0
5  -2.070537  1.518549      0
6  -2.445711  0.074563      0
7  -2.233842  0.247614      0
8  -2.341958 -1.095146      0
9  -2.188676 -0.448629      0
10 -2.163487  1.070596      0
11 -2.327378  0.158587      0
12 -2.224083 -0.709118      0
13 -2.639716 -0.938282      0
14 -2.192292  1.889979      0
15 -2.251465  2.722371      0
16 -2.202750  1.513750      0
17 -2.190179  0.514304      0
18 -1.894074  1.431111      0
19 -2.339949  1.158033      0
20 -1.914556  0.430465      0
21 -2.204645  0.952457      0
22 -2.774170  0.489517      0
23 -1.820412  0.106751      0
24 -2.228217  0.162186      0
25 -1.957024 -0.607893      0
26 -2.052063  0.266014      0
27 -2.168194  0.552016      0
28 -2.140306  0.336640      0
29 -2.268790 -0.314879      0
30 -2.144554 -0.483942      0
31 -1.831938  0.445267      0
32 -2.608203  1.828475      0
33 -2.437951  2.185392      0
34 -2.188676 -0.448629      0
35 -2.211120 -0.184338      0
36 -2.044417  0.684956      0
37 -2.188676 -0.448629      0
38 -2.435952 -0.882169      0
39 -2.170547  0.292727      0
40 -2.286527  0.467992      0
41 -1.871707 -2.327692      0
42 -2.557834 -0.453816      0
43 -1.964279  0.497392      0
44 -2.133373  1.171432      0
45 -2.075358 -0.691917      0
46 -2.381258  1.150633      0
47 -2.398192 -0.362391      0
48 -2.226781  1.025483      0
49 -2.205954  0.032238      0

In [32]:
d2 = df2[df2['label'] == 'Iris-versicolor']
d2['label'] = 1
d2

/home/mehul/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


pc1       pc2  label
50  1.103994  0.863112      1
51  0.732481  0.598636      1
52  1.242110  0.614822      1
53  0.397307 -1.758169      1
54  1.072594 -0.211758      1
55  0.384458 -0.591062      1
56  0.748715  0.778699      1
57 -0.497863 -1.848869      1
58  0.926222  0.030331      1
59  0.004968 -1.029401      1
60 -0.124697 -2.658063      1
61  0.438730 -0.058881      1
62  0.551634 -1.772582      1
63  0.717165 -0.185434      1
64 -0.037258 -0.432795      1
65  0.875891  0.509998      1
66  0.348006 -0.190622      1
67  0.153393 -0.790725      1
68  1.215303 -1.633356      1
69  0.156941 -1.303103      1
70  0.738256  0.402470      1
71  0.472370 -0.416608      1
72  1.227988 -0.940915      1
73  0.629381 -0.416812      1
74  0.700473 -0.063494      1
75  0.873537  0.250709      1
76  1.254222 -0.082620      1
77  1.358240  0.328820      1
78  0.662126 -0.224346      1
79 -0.047282 -1.057212      1
80  0.121534 -1.563592      1
81  0.014118 -1.573392      1
82  0.236011 -0.775924      1
83  1.056691 -0.636901      1
84  0.221417 -0.280848      1
85  0.431783  0.855137      1
86  1.049413  0.522197      1
87  1.035878 -1.392466      1
88  0.067068 -0.212621      1
89  0.275425 -1.329816      1
90  0.272335 -1.119442      1
91  0.623171  0.027543      1
92  0.330005 -0.988901      1
93 -0.373628 -2.017932      1
94  0.282944 -0.853951      1
95  0.089053 -0.174909      1
96  0.224357 -0.380485      1
97  0.573883 -0.153720      1
98 -0.457013 -1.539465      1
99  0.252244 -0.595861      1

In [33]:
d3 = df2[df2['label'] == 'Iris-virginica']
d3['label'] = 2
d3

/home/mehul/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


pc1       pc2  label
100  1.847673  0.871697      2
101  1.153190 -0.701326      2
102  2.206349  0.554470      2
103  1.438685 -0.050011      2
104  1.867891  0.291193      2
105  2.754197  0.788432      2
106  0.358374 -1.560095      2
107  2.303006  0.409517      2
108  2.001735 -0.723865      2
109  2.267555  1.921443      2
110  1.365909  0.693948      2
111  1.599065 -0.428249      2
112  1.884252  0.414333      2
113  1.253087 -1.167391      2
114  1.464062 -0.444148      2
115  1.591809  0.677035      2
116  1.471280  0.253192      2
117  2.437378  2.556757      2
118  3.309141 -0.002361      2
119  1.253981 -1.717584      2
120  2.040496  0.907399      2
121  0.973915 -0.571174      2
122  2.898064  0.397791      2
123  1.329194 -0.486761      2
124  1.704241  1.014148      2
125  1.957728  1.003335      2
126  1.171905 -0.318897      2
127  1.019781  0.065543      2
128  1.786009 -0.193273      2
129  1.864778  0.555382      2
130  2.435497  0.246654      2
131  2.316082  2.626184      2
132  1.860371 -0.184672      2
133  1.111272 -0.295986      2
134  1.197469 -0.817168      2
135  2.800949  0.844748      2
136  1.580155  1.072474      2
137  1.347044  0.422256      2
138  0.923433  0.019230      2
139  1.853552  0.672423      2
140  2.016157  0.610397      2
141  1.903117  0.686025      2
142  1.153190 -0.701326      2
143  2.043308  0.864685      2
144  2.001691  1.048550      2
145  1.870522  0.382822      2
146  1.558492 -0.905314      2
147  1.520845  0.266795      2
148  1.376391  1.016362      2
149  0.959299 -0.022284      2

In [34]:
d_combined = pd.concat([d1, d2, d3])
d_combined

pc1       pc2  label
0   -2.264542  0.505704      0
1   -2.086426 -0.655405      0
2   -2.367950 -0.318477      0
3   -2.304197 -0.575368      0
4   -2.388777  0.674767      0
5   -2.070537  1.518549      0
6   -2.445711  0.074563      0
7   -2.233842  0.247614      0
8   -2.341958 -1.095146      0
9   -2.188676 -0.448629      0
10  -2.163487  1.070596      0
11  -2.327378  0.158587      0
12  -2.224083 -0.709118      0
13  -2.639716 -0.938282      0
14  -2.192292  1.889979      0
15  -2.251465  2.722371      0
16  -2.202750  1.513750      0
17  -2.190179  0.514304      0
18  -1.894074  1.431111      0
19  -2.339949  1.158033      0
20  -1.914556  0.430465      0
21  -2.204645  0.952457      0
22  -2.774170  0.489517      0
23  -1.820412  0.106751      0
24  -2.228217  0.162186      0
25  -1.957024 -0.607893      0
26  -2.052063  0.266014      0
27  -2.168194  0.552016      0
28  -2.140306  0.336640      0
29  -2.268790 -0.314879      0
..        ...       ...    ...
120  2.040496  0.907399      2
121  0.973915 -0.571174      2
122  2.898064  0.397791      2
123  1.329194 -0.486761      2
124  1.704241  1.014148      2
125  1.957728  1.003335      2
126  1.171905 -0.318897      2
127  1.019781  0.065543      2
128  1.786009 -0.193273      2
129  1.864778  0.555382      2
130  2.435497  0.246654      2
131  2.316082  2.626184      2
132  1.860371 -0.184672      2
133  1.111272 -0.295986      2
134  1.197469 -0.817168      2
135  2.800949  0.844748      2
136  1.580155  1.072474      2
137  1.347044  0.422256      2
138  0.923433  0.019230      2
139  1.853552  0.672423      2
140  2.016157  0.610397      2
141  1.903117  0.686025      2
142  1.153190 -0.701326      2
143  2.043308  0.864685      2
144  2.001691  1.048550      2
145  1.870522  0.382822      2
146  1.558492 -0.905314      2
147  1.520845  0.266795      2
148  1.376391  1.016362      2
149  0.959299 -0.022284      2

[150 rows x 3 columns]

In [36]:
df2.corr()

pc1           pc2
pc1  1.000000e+00 -1.868982e-16
pc2 -1.868982e-16  1.000000e+00

In [37]:
x_data = d_combined[['pc1', 'pc2']].values
y_data = d_combined['label'].values
print(x_data)
print(y_data)

[[ -2.26454173e+00   5.05703903e-01]
 [ -2.08642550e+00  -6.55404729e-01]
 [ -2.36795045e+00  -3.18477311e-01]
 [ -2.30419716e+00  -5.75367713e-01]
 [ -2.38877749e+00   6.74767397e-01]
 [ -2.07053681e+00   1.51854856e+00]
 [ -2.44571134e+00   7.45626750e-02]
 [ -2.23384186e+00   2.47613932e-01]
 [ -2.34195768e+00  -1.09514636e+00]
 [ -2.18867576e+00  -4.48629048e-01]
 [ -2.16348656e+00   1.07059558e+00]
 [ -2.32737775e+00   1.58587455e-01]
 [ -2.22408272e+00  -7.09118158e-01]
 [ -2.63971626e+00  -9.38281982e-01]
 [ -2.19229151e+00   1.88997851e+00]
 [ -2.25146521e+00   2.72237108e+00]
 [ -2.20275048e+00   1.51375028e+00]
 [ -2.19017916e+00   5.14304308e-01]
 [ -1.89407429e+00   1.43111071e+00]
 [ -2.33994907e+00   1.15803343e+00]
 [ -1.91455639e+00   4.30465163e-01]
 [ -2.20464540e+00   9.52457317e-01]
 [ -2.77416979e+00   4.89517027e-01]
 [ -1.82041156e+00   1.06750793e-01]
 [ -2.22821750e+00   1.62186163e-01]
 [ -1.95702401e+00  -6.07892567e-01]
 [ -2.05206331e+00   2.66014312e-01]
 

In [38]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.2)

In [39]:
lr1 = LinearRegression()
lr1.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [40]:
y_pred = lr1.predict(x_test)

In [41]:
lr1.score(x_train, y_train)

0.89304179510414139

In [43]:
print(mean_absolute_error(y_test, y_pred))
print(np.sqrt(mean_squared_error(y_test, y_pred)))

0.201941287275
0.262333893912
