In [1]:
import numpy as np

In [2]:
marks = [
    [91, 93, 100],
    [96, 97, 94],
    [99, 87, 80]
]
n1 = np.array(marks, dtype=np.int16)
print(n1)
print(n1.shape)
print(n1.ndim)

[[ 91  93 100]
 [ 96  97  94]
 [ 99  87  80]]
(3, 3)
2


In [15]:
# indexing
print(n1[-1])
print(n1[-1, 1])
print(n1[0, -1])
# multiple indexing
print(n1[[0, -1]])
print(n1[[0, -1], 1])
n2 = n1[[0, -1]]
print(n2[[0, 1], 0])
print(n2[[0, 1], -1])

[99 87 80]
87
100
[[ 91  93 100]
 [ 99  87  80]]
[93 87]
[91 99]
[100  80]


In [20]:
# slicing
print(n1)
print(n1[:2])
print(n1[:2, :2])
print(n1[1:, -1]) # slicing + indexing
print(n1[[0, -1], 1:])

[[ 91  93 100]
 [ 96  97  94]
 [ 99  87  80]]
[[ 91  93 100]
 [ 96  97  94]]
[[91 93]
 [96 97]]
[94 80]
[[ 93 100]
 [ 87  80]]


In [24]:
print(n1)
print(n1.sum(axis=1))
print(n1.mean(axis=0))

[[ 91  93 100]
 [ 96  97  94]
 [ 99  87  80]]
[284 287 266]
[ 95.33333333  92.33333333  91.33333333]


In [29]:
print(n1)
# Vectorized
print(n1-1)
print(n1 - [0, 1, 0])
print(n1 - [
    [1],
    [0],
    [2]
])
print(n1 - [
    [1, 0, 0],
    [0, 0, 0],
    [2, 0, 0]
])

[[ 91  93 100]
 [ 96  97  94]
 [ 99  87  80]]
[[90 92 99]
 [95 96 93]
 [98 86 79]]
[[ 91  92 100]
 [ 96  96  94]
 [ 99  86  80]]
[[90 92 99]
 [96 97 94]
 [97 85 78]]
[[ 90  93 100]
 [ 96  97  94]
 [ 97  87  80]]


In [35]:
print(np.identity(3))
n2 = np.arange(1, 10).reshape(3,3)
print(n2)
n3 = n2.ravel()
print(n3)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [37]:
n3 = np.array([
    [4, 5],
    [3, 2]
])
n4 = np.array([
    [1, 2],
    [5, 3]
])
print(n3)
print(n4)

[[4 5]
 [3 2]]
[[1 2]
 [5 3]]


In [41]:
print(n3 + n4)
print(n3 - n4)
print(n3 * n4) # this is not matrix multiplication
n5 = np.dot(n3, n4) # true mathematical matrix multiplication
print(n5)

[[5 7]
 [8 5]]
[[ 3  3]
 [-2 -1]]
[[ 4 10]
 [15  6]]
[[29 23]
 [13 12]]
