In [35]:
print('Hello World')
print('Hello Night')

Hello World
Hello Night


In [36]:
for v in range(1, 8):
    print(v)

1
2
3
4
5
6
7


In [37]:
import numpy as np

In [38]:
# ndarray
pointers = [3, 4, 5, 7, 5, 10, 1, 5, 6, 9, 10]
n1 = np.array(pointers, dtype=np.int16)
print(n1)
print(type(n1))
print(n1.shape)
print(n1.ndim)
print(n1.dtype)

[ 3  4  5  7  5 10  1  5  6  9 10]
<class 'numpy.ndarray'>
(11,)
1
int16


In [39]:
# indexing
print(n1[0])
print(n1[1])
print(n1[-1])
print(n1[-3])
print(n1[[0, -1]]) # Multiple indexing

3
4
10
6
[ 3 10]


In [40]:
# slicing
print(n1[:3])
print(n1[-4:])

[3 4 5]
[ 5  6  9 10]


In [41]:
# relational operators on numpy array
print(n1 >= 5)
print(n1 == 10)

[False False  True  True  True  True False  True  True  True  True]
[False False False False False  True False False False False  True]


In [42]:
# Vectorized operations
# Get an array of marks from n1, but deducted by 1
n2 = n1 - 1
print(n2)

[2 3 4 6 4 9 0 4 5 8 9]


In [43]:
# Filtering elements from a numpy array
# Get an array of marks from n1, but odds more than or equal 5
n3 = n1[(n1 % 2 != 0) & (n1 >= 5)]
print(n3)

[5 7 5 5 9]


In [44]:
# Get all even element less than 5
n4 = n1[(n1 % 2 == 0) & (n1 < 5)]
print(n4)

[4]


In [45]:
# Vectorized branching
print(n1)
n5 = np.where(n1 > 5, 1, 0)
print(n5)

[ 3  4  5  7  5 10  1  5  6  9 10]
[0 0 0 1 0 1 0 0 1 1 1]


In [51]:
# Mathematical operations
print(n1)
print(n1.min())
print(n1.max())
print(n1.mean())
print(n1.std())
print(n1.var())
print(n1.cumsum())
s = np.sort(n1)
print(s)

[ 3  4  5  7  5 10  1  5  6  9 10]
1
10
5.90909090909
2.7453943401
7.53719008264
[ 3  7 12 19 24 34 35 40 46 55 65]
[ 1  3  4  5  5  5  6  7  9 10 10]


In [54]:
# number generating capability
print(np.ones(10))
print(np.zeros(20))
print(np.arange(5, 16))

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.]
[ 5  6  7  8  9 10 11 12 13 14 15]
